env: {}

name: Release extensions
on:
  workflow_dispatch: null
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/daily-version-action@v1
        name: Create tag if necessary
        id: daily-version
    outputs:
      created: '${{ steps.daily-version.outputs.created }}'
      version: '${{ steps.daily-version.outputs.version }}'
  chrome:
    needs: version
    if: github.event_name == 'workflow_dispatch' || needs.version.outputs.created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Update extension version
        run: >-
          npx dot-json extension/manifest.json version ${{
          needs.version.outputs.version }}
      - run: 'npm run release:chrome'
        env:
          EXTENSION_ID: '${{ secrets.EXTENSION_ID }}'
          CLIENT_ID: '${{ secrets.CLIENT_ID }}'
          CLIENT_SECRET: '${{ secrets.CLIENT_SECRET }}'
          REFRESH_TOKEN: '${{ secrets.REFRESH_TOKEN }}'
  firefox:
    needs: version
    if: github.event_name == 'workflow_dispatch' || needs.version.outputs.created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Update extension version
        run: >-
          npx dot-json extension/manifest.json version ${{
          needs.version.outputs.version }}
      - name: Sign extension
        run: npm run release:firefox
        env:
          WEB_EXT_API_KEY: '${{ secrets.WEB_EXT_API_KEY }}'
          WEB_EXT_API_SECRET: '${{ secrets.WEB_EXT_API_SECRET }}'
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.version.outputs.version }}
          release_name: Firefox extension v${{ needs.version.outputs.version }}
          draft: false
          prerelease: false
      - name: Find signed extension
        run: |
          FILENAME=$(ls extension/web-ext-artifacts)
          echo "::set-output name=ext_file::$FILENAME"
        id: find
      - name: Update Firefox update manifest
        run: |
          wget https://github.com/${{ github.repository }}/releases/latest/download/firefox-updates.json
          echo "`jq '.addons[].updates += [{\"version\": \"${{
          needs.version.outputs.version }}\", \"update_link\": \"https://github.com/${{
          github.repository }}/releases/download/${{ needs.version.outputs.version
          }}/firefox-extension.xpi\"}]' firefox-updates.json`" > firefox-updates.json
      - name: Upload XPI
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension/web-ext-artifacts/${{ steps.find.outputs.ext_file }}
          asset_name: firefox-extension.xpi
          asset_content_type: application/x-xpinstall
      - name: Upload update manifest
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./firefox-updates.json
          asset_name: firefox-updates.json
          asset_content_type: application/json
