env: {}

name: Release extensions
on:
  workflow_dispatch: null
jobs:
  version:
    outputs:
      created: '${{ steps.daily-version.outputs.created }}'
      version: '${{ steps.daily-version.outputs.version }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - uses: fregante/daily-version-action@v1
        name: Create tag if necessary
        id: daily-version
      - uses: notlmn/release-with-changelog@v3
        if: steps.daily-version.outputs.created
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          exclude: true
  submit:
    needs: version
    if: github.event_name == 'workflow_dispatch' || needs.Version.outputs.created
    strategy:
      fail-fast: false
      matrix:
        command:
          - firefox
          - chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Update extension’s meta
        run: >-
          npx dot-json extension/manifest.json version ${{
          needs.Version.outputs.version }}
      - run: 'npm run release:${{ matrix.command }}'
        env:
          EXTENSION_ID: '${{ secrets.EXTENSION_ID }}'
          CLIENT_ID: '${{ secrets.CLIENT_ID }}'
          CLIENT_SECRET: '${{ secrets.CLIENT_SECRET }}'
          REFRESH_TOKEN: '${{ secrets.REFRESH_TOKEN }}'
          WEB_EXT_API_KEY: '${{ secrets.WEB_EXT_API_KEY }}'
          WEB_EXT_API_SECRET: '${{ secrets.WEB_EXT_API_SECRET }}'
